//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Imagenes
    {
        public int idImagen { get; set; }
        public string Imagen { get; set; }
        public bool Activo { get; set; }
        public int RazaId { get; set; }
    
        public virtual tb_Razas tb_Razas { get; set; }
    }
}
